env:    
language: node_js
node_js: "6"
os: linux
dist: trusty
install: 
    - yarn global add gulp-cli
    - yarn install
script: cd ./integration_tests/ && mocha pipeline_builder_functional_test.js
